# -*- coding: utf-8 -*-
"""
Base das ferramentas que alimenta o painel de Tecnologia da home.

Campos por ferramenta:
  nome, grupo, icone, etapa, licenca, modelo,
  oque, negocio, melhor, para, como, mercado, caso

etapa    — onde a ferramenta atua no fluxo do painel:
           'origem' | 'base' | 'dash' | 'todas' (atravessa as três)
licenca  — fato verificável: 'Open source', 'Proprietária', 'Aberto + pago', 'Padrão aberto'
modelo   — fato verificável: 'SaaS', 'Self-hosted', 'SaaS ou self-hosted', 'API', 'Biblioteca'
mercado  — leitura editorial da Atlas sobre onde a ferramenta costuma aparecer.
           NÃO é participação de mercado medida: não existe fonte para isso aqui,
           e número inventado destruiria a credibilidade do resto do painel.
caso     — só preenchido quando há projeto realmente entregue pela Atlas.
"""

GRUPOS = [
    ('bi',    'BI &amp; Data Visualization'),
    ('plat',  'Data Platform'),
    ('eng',   'Data Engineering'),
    ('cloud', 'Cloud'),
    ('ia',    'Inteligência Artificial'),
    ('db',    'Bancos de dados'),
    ('gov',   'Governança'),
    ('ds',    'Analytics &amp; Data Science'),
]

ETAPAS = [
    ('origem', 'Origem', 'Onde o dado nasce: os sistemas que a empresa já usa.'),
    ('base',   'Base de dados', 'Onde o dado é reunido, tratado e fica confiável.'),
    ('dash',   'Dashboards', 'Onde o dado vira leitura e decisão.'),
]

F = [
 # ---------------------------------------------------------------- BI
 dict(nome='Power BI', grupo='bi', icone='#PBI', etapa='dash',
      licenca='Proprietária', modelo='SaaS + desktop',
      oque='Dashboards executivos e self-service BI para as áreas.',
      negocio='A área deixa de pedir relatório e passa a responder a própria pergunta.',
      melhor='Colocar indicador confiável na mão de quem não é técnico.',
      para='Empresa que já vive no ecossistema Microsoft e precisa de BI corporativo.',
      como='Modelo publicado num workspace, com métrica definida em DAX e atualização agendada.',
      mercado='Padrão de fato em empresas que já usam Microsoft 365.',
      caso='Plataforma omnichannel de varejo, com indicadores de venda e operação por canal.'),
 dict(nome='Tableau', grupo='bi', icone='tableau', etapa='dash',
      licenca='Proprietária', modelo='SaaS ou self-hosted',
      oque='Exploração visual de grandes volumes de dados.',
      negocio='O analista encontra o padrão antes de alguém pedir o relatório.',
      melhor='Descobrir o que está acontecendo quando ainda não se sabe o que perguntar.',
      para='Time de análise que explora antes de publicar.',
      como='Conecta à base, monta a visão arrastando campos e publica no servidor.',
      mercado='Forte em times analíticos que priorizam exploração sobre padronização.',
      caso='Rede de diagnóstico, na migração da visualização para Power BI.'),
 dict(nome='Looker', grupo='bi', icone='looker', etapa='dash',
      licenca='Proprietária', modelo='SaaS',
      oque='Camada semântica única sobre o dado.',
      negocio='Uma métrica, uma definição — fim da divergência entre áreas.',
      melhor='Garantir que receita signifique a mesma coisa em toda a empresa.',
      para='Organização com muitas áreas e histórico de números divergentes.',
      como='As métricas são escritas em LookML, versionadas em Git, e todo painel as reusa.',
      mercado='Escolha comum em empresas no Google Cloud que priorizam governança de métrica.',
      caso='Mais de 200 dashboards migrados num projeto de governança de BI.'),
 dict(nome='Qlik', grupo='bi', icone='qlik', etapa='dash',
      licenca='Proprietária', modelo='SaaS ou self-hosted',
      oque='BI associativo, com exploração livre entre dimensões.',
      negocio='A pergunta seguinte não depende de um novo relatório.',
      melhor='Navegar entre dimensões sem caminho pré-definido.',
      para='Análise exploratória em bases grandes e relacionadas.',
      como='O modelo associativo carrega em memória e o filtro se propaga por tudo.',
      mercado='Base instalada relevante em indústria e varejo de médio e grande porte.',
      caso=''),
 dict(nome='MicroStrategy', grupo='bi', icone='microstrategy', etapa='dash',
      licenca='Proprietária', modelo='SaaS ou self-hosted',
      oque='BI corporativo para operações multiárea.',
      negocio='Vendas, logística e operação lendo os mesmos números.',
      melhor='Servir muitas áreas com governança central e controle fino de acesso.',
      para='Operação grande, com muitos perfis de usuário e exigência de auditoria.',
      como='Metadados centralizados alimentam relatórios e painéis por perfil.',
      mercado='Presença consolidada em grandes corporações com BI legado maduro.',
      caso='BI corporativo em varejo de moda e arquitetura ETL → DW → BI em turismo.'),
 dict(nome='Metabase', grupo='bi', icone='metabase', etapa='dash',
      licenca='Aberto + pago', modelo='SaaS ou self-hosted',
      oque='BI open source de implantação rápida.',
      negocio='Os primeiros indicadores no ar sem um projeto longo.',
      melhor='Sair do zero para o primeiro painel em dias, não em meses.',
      para='Time enxuto que precisa começar a medir agora.',
      como='Conecta ao banco e monta pergunta por interface ou SQL direto.',
      mercado='Muito usado por startups e times de produto antes do BI corporativo.',
      caso=''),
 dict(nome='Superset', grupo='bi', icone='superset', etapa='dash',
      licenca='Open source', modelo='Self-hosted',
      oque='Visualização open source sobre SQL.',
      negocio='Painéis corporativos sem custo de licença por assento.',
      melhor='Escalar número de usuários sem escalar custo de licença.',
      para='Empresa com time técnico próprio e muitos leitores de painel.',
      como='Roda na infraestrutura da empresa, lendo direto do warehouse.',
      mercado='Adotado por empresas de tecnologia com engenharia de dados madura.',
      caso=''),
 # ---------------------------------------------------------------- Data Platform
 dict(nome='Databricks', grupo='plat', icone='databricks', etapa='base',
      licenca='Proprietária', modelo='SaaS',
      oque='Lakehouse e processamento de dados em escala.',
      negocio='Volume deixa de ser o limite da análise.',
      melhor='Processar volume alto e servir engenharia, análise e IA no mesmo lugar.',
      para='Operação com terabytes e time de engenharia próprio.',
      como='Notebooks e jobs em Spark sobre tabelas Delta, com catálogo unificado.',
      mercado='Referência em empresas que tratam dados como plataforma, não como relatório.',
      caso='Pipelines da plataforma omnichannel em Azure.'),
 dict(nome='Snowflake', grupo='plat', icone='snowflake', etapa='base',
      licenca='Proprietária', modelo='SaaS',
      oque='Data warehouse em nuvem com escala elástica.',
      negocio='O custo acompanha o uso, não o pico.',
      melhor='Separar processamento de armazenamento e pagar só pelo que roda.',
      para='Quem tem demanda irregular e não quer dimensionar para o pico.',
      como='O warehouse liga para a consulta e desliga sozinho depois.',
      mercado='Muito presente em empresas que migraram de warehouse local para nuvem.',
      caso=''),
 dict(nome='BigQuery', grupo='plat', icone='bigquery', etapa='base',
      licenca='Proprietária', modelo='SaaS',
      oque='Data warehouse analítico gerenciado do Google.',
      negocio='Consulta pesada sem infraestrutura para administrar.',
      melhor='Rodar consulta grande sem ninguém cuidar de servidor.',
      para='Quem já está no Google Cloud ou quer começar sem operação.',
      como='SQL direto no console, com cobrança por dado lido.',
      mercado='Porta de entrada analítica mais comum dentro do Google Cloud.',
      caso='Data Lake em GCP para serviços financeiros e pipelines em saúde.'),
 dict(nome='Microsoft Fabric', grupo='plat', icone='#FAB', etapa='base',
      licenca='Proprietária', modelo='SaaS',
      oque='Plataforma unificada de dados e BI da Microsoft.',
      negocio='Um ambiente só, do pipeline ao relatório.',
      melhor='Reunir ingestão, armazenamento e Power BI sob um contrato.',
      para='Empresa Microsoft que quer reduzir número de ferramentas.',
      como='Tudo num workspace, com o OneLake como armazenamento comum.',
      mercado='Adoção crescente em quem já tinha Power BI e quer unificar o resto.',
      caso=''),
 dict(nome='Redshift', grupo='plat', icone='redshift', etapa='base',
      licenca='Proprietária', modelo='SaaS',
      oque='Data warehouse da AWS.',
      negocio='Escala analítica dentro do ecossistema Amazon.',
      melhor='Ficar perto do dado que já vive na AWS.',
      para='Quem tem a operação toda em AWS e quer evitar travessia de nuvem.',
      como='Clusters ou serverless, lendo também direto do S3.',
      mercado='Escolha natural de quem já é AWS de ponta a ponta.',
      caso=''),
 # ---------------------------------------------------------------- Data Engineering
 dict(nome='dbt', grupo='eng', icone='dbt', etapa='base',
      licenca='Aberto + pago', modelo='Self-hosted ou SaaS',
      oque='Transformação versionada e testada.',
      negocio='A regra de negócio deixa de morar na cabeça de uma pessoa.',
      melhor='Transformar SQL solto em código com teste, versão e documentação.',
      para='Time que já tem warehouse e precisa confiar no que está dentro dele.',
      como='Modelos em SQL versionados em Git, com testes que rodam no pipeline.',
      mercado='Virou padrão da camada de transformação no stack moderno de dados.',
      caso='Transformações do Data Lake em GCP.'),
 dict(nome='Airflow', grupo='eng', icone='airflow', etapa='base',
      licenca='Open source', modelo='Self-hosted ou gerenciado',
      oque='Orquestração de pipelines.',
      negocio='O dado chega na hora certa, e a falha aparece antes do usuário.',
      melhor='Coordenar dezenas de rotinas com dependência entre elas.',
      para='Operação com muitas cargas que precisam rodar em ordem.',
      como='O fluxo é escrito em Python e agendado como grafo de tarefas.',
      mercado='Orquestrador mais difundido em engenharia de dados.',
      caso='Pipelines em GCP para serviços financeiros e saúde.'),
 dict(nome='Spark', grupo='eng', icone='spark', etapa='base',
      licenca='Open source', modelo='Self-hosted ou gerenciado',
      oque='Processamento distribuído.',
      negocio='Terabytes processados dentro da janela da madrugada.',
      melhor='Quebrar um processamento grande entre muitas máquinas.',
      para='Volume que não cabe em uma máquina só.',
      como='O mesmo código roda em um notebook e em um cluster de produção.',
      mercado='Motor por trás de boa parte das plataformas de dados em escala.',
      caso=''),
 dict(nome='Fivetran', grupo='eng', icone='#FVT', etapa='origem',
      licenca='Proprietária', modelo='SaaS',
      oque='Conectores gerenciados de ingestão.',
      negocio='A fonte muda e o conector acompanha.',
      melhor='Tirar da equipe a manutenção de conector de sistema de terceiro.',
      para='Quem tem muitas fontes SaaS e pouca gente para cuidar delas.',
      como='Escolhe a fonte, autentica e a carga passa a rodar sozinha.',
      mercado='Opção comum quando o custo do conector é menor que o da equipe.',
      caso=''),
 dict(nome='Airbyte', grupo='eng', icone='airbyte', etapa='origem',
      licenca='Aberto + pago', modelo='Self-hosted ou SaaS',
      oque='Ingestão open source com conectores abertos.',
      negocio='Fonte de nicho sem esperar o fornecedor.',
      melhor='Conectar a fonte que nenhum catálogo comercial cobre.',
      para='Quem tem sistema interno ou de nicho para integrar.',
      como='Conector pronto do catálogo aberto, ou escrito pela própria equipe.',
      mercado='Cresce onde a lista de fontes é longa e heterogênea.',
      caso=''),
 dict(nome='Kafka', grupo='eng', icone='kafka', etapa='origem',
      licenca='Open source', modelo='Self-hosted ou gerenciado',
      oque='Streaming de eventos.',
      negocio='O dado deixa de esperar o lote da noite.',
      melhor='Transportar evento no instante em que ele acontece.',
      para='Operação em que atraso de horas custa dinheiro.',
      como='Sistemas publicam eventos em tópicos; vários consumidores leem em paralelo.',
      mercado='Espinha dorsal de arquitetura em tempo real na maioria dos setores.',
      caso=''),
 # ---------------------------------------------------------------- Cloud
 dict(nome='Azure', grupo='cloud', icone='#AZ', etapa='todas',
      licenca='Proprietária', modelo='Nuvem',
      oque='Nuvem Microsoft para dados e analytics.',
      negocio='Integra com o que a empresa já usa no dia a dia.',
      melhor='Aproveitar identidade, licença e governança que a empresa já tem.',
      para='Organização que já roda Microsoft na operação.',
      como='Data Factory, Synapse e Databricks sob a mesma assinatura.',
      mercado='Nuvem preferida de quem tem base corporativa Microsoft.',
      caso='Synapse e Data Factory na plataforma omnichannel.'),
 dict(nome='AWS', grupo='cloud', icone='aws', etapa='todas',
      licenca='Proprietária', modelo='Nuvem',
      oque='Nuvem com o portfólio mais amplo de serviços.',
      negocio='Escala sem reescrever a arquitetura.',
      melhor='Ter um serviço gerenciado para quase qualquer necessidade.',
      para='Quem precisa de amplitude e de maturidade operacional.',
      como='S3 como base, com Glue, Athena e Redshift em volta.',
      mercado='Maior amplitude de serviços entre as nuvens públicas.',
      caso=''),
 dict(nome='Google Cloud', grupo='cloud', icone='googlecloud', etapa='todas',
      licenca='Proprietária', modelo='Nuvem',
      oque='Nuvem Google, forte em analytics e IA.',
      negocio='BigQuery e IA no mesmo lugar em que o dado já está.',
      melhor='Analisar e aplicar IA sem mover o dado de lugar.',
      para='Quem quer começar analítico sem montar infraestrutura.',
      como='BigQuery no centro, com Vertex AI e Looker ao redor.',
      mercado='Forte entre empresas que começam pela analítica.',
      caso='Data Lake em GCP e migração de legado Oracle.'),
 # ---------------------------------------------------------------- IA
 dict(nome='OpenAI', grupo='ia', icone='openai', etapa='dash',
      licenca='Proprietária', modelo='API',
      oque='Modelos de linguagem de uso geral via API.',
      negocio='Capacidade de IA sem treinar modelo do zero.',
      melhor='Colocar linguagem natural sobre processo que hoje é manual.',
      para='Quem quer resultado rápido sem montar time de machine learning.',
      como='Chamada de API a partir da aplicação, com o contexto do negócio junto.',
      mercado='Ponto de partida mais comum para IA generativa em empresa.',
      caso=''),
 dict(nome='Anthropic', grupo='ia', icone='anthropic', etapa='dash',
      licenca='Proprietária', modelo='API',
      oque='Modelos Claude, com foco em uso corporativo.',
      negocio='IA sobre documento e análise, com controle do contexto.',
      melhor='Trabalhar sobre textos longos mantendo o fio do raciocínio.',
      para='Análise de contrato, relatório e base documental.',
      como='API com o documento e as regras da empresa no contexto.',
      mercado='Escolha frequente quando o caso envolve documento extenso.',
      caso=''),
 dict(nome='Gemini', grupo='ia', icone='gemini', etapa='dash',
      licenca='Proprietária', modelo='API',
      oque='Modelos multimodais do Google, integrados ao Cloud.',
      negocio='IA ao lado do dado que já está no BigQuery.',
      melhor='Aplicar IA sem tirar o dado do ambiente onde ele vive.',
      para='Quem já tem a analítica dentro do Google Cloud.',
      como='Chamada direta pelo Vertex AI, com acesso ao warehouse.',
      mercado='Caminho natural de IA para quem já é Google Cloud.',
      caso=''),
 dict(nome='Hugging Face', grupo='ia', icone='huggingface', etapa='dash',
      licenca='Aberto + pago', modelo='Biblioteca e SaaS',
      oque='Modelos abertos prontos para uso.',
      negocio='Começar de um modelo treinado, não do zero.',
      melhor='Achar um modelo aberto que já resolve o problema.',
      para='Caso específico em que modelo geral não serve.',
      como='Baixa o modelo do repositório e roda na própria infraestrutura.',
      mercado='Repositório de referência para modelos abertos.',
      caso=''),
 dict(nome='MLflow', grupo='ia', icone='mlflow', etapa='base',
      licenca='Open source', modelo='Self-hosted ou gerenciado',
      oque='Ciclo de vida de modelos.',
      negocio='Modelo em produção com histórico e reversão.',
      melhor='Saber qual versão do modelo gerou qual resultado.',
      para='Quem já tem modelo em produção e precisa de controle.',
      como='Cada treino fica registrado com parâmetro, métrica e artefato.',
      mercado='Padrão de fato para rastreabilidade de experimentos.',
      caso=''),
 # ---------------------------------------------------------------- Bancos
 dict(nome='PostgreSQL', grupo='db', icone='postgresql', etapa='origem',
      licenca='Open source', modelo='Self-hosted ou gerenciado',
      oque='Banco relacional open source.',
      negocio='Base robusta sem custo de licença.',
      melhor='Aguentar carga séria sem cobrar por isso.',
      para='Aplicação própria e base analítica de porte médio.',
      como='Fonte do produto, replicada para não pesar na operação.',
      mercado='Banco relacional aberto mais usado em aplicação nova.',
      caso=''),
 dict(nome='SQL Server', grupo='db', icone='#SQLS', etapa='origem',
      licenca='Proprietária', modelo='Self-hosted ou gerenciado',
      oque='Banco relacional corporativo da Microsoft.',
      negocio='O sistema que roda a empresa vira fonte analítica.',
      melhor='Sustentar ERP e sistema crítico com ferramental maduro.',
      para='Empresa com sistema corporativo sobre plataforma Microsoft.',
      como='Réplica de leitura alimenta o pipeline sem afetar a operação.',
      mercado='Muito presente no back-end de ERP corporativo no Brasil.',
      caso=''),
 dict(nome='Oracle', grupo='db', icone='oracle', etapa='origem',
      licenca='Proprietária', modelo='Self-hosted ou nuvem',
      oque='Banco de missão crítica.',
      negocio='O legado segue de pé enquanto a análise avança.',
      melhor='Sustentar transação crítica com décadas de ajuste fino.',
      para='Core bancário, seguro e industrial de grande porte.',
      como='Extração incremental para a nuvem, sem tocar no núcleo.',
      mercado='Domina núcleos transacionais antigos de grandes empresas.',
      caso='Migração de legado Oracle em projeto de nuvem.'),
 dict(nome='MongoDB', grupo='db', icone='mongodb', etapa='origem',
      licenca='Aberto + pago', modelo='Self-hosted ou SaaS',
      oque='Banco de documentos.',
      negocio='Dado semiestruturado sem forçar tabela.',
      melhor='Guardar registro cujo formato muda com o tempo.',
      para='Produto digital, catálogo e evento de aplicação.',
      como='Documentos achatados no pipeline antes de virar tabela analítica.',
      mercado='Banco de documentos mais usado em aplicação moderna.',
      caso=''),
 dict(nome='Redis', grupo='db', icone='redis', etapa='origem',
      licenca='Aberto + pago', modelo='Self-hosted ou SaaS',
      oque='Banco em memória, de resposta imediata.',
      negocio='O painel não espera pela consulta pesada.',
      melhor='Responder em milissegundos o que seria caro recalcular.',
      para='Contador, sessão e indicador de tempo real.',
      como='Camada de cache entre a aplicação e o banco principal.',
      mercado='Padrão de cache na maior parte das arquiteturas web.',
      caso=''),
 dict(nome='Elasticsearch', grupo='db', icone='elasticsearch', etapa='origem',
      licenca='Aberto + pago', modelo='Self-hosted ou SaaS',
      oque='Busca e análise sobre texto e log.',
      negocio='Achar o registro certo num volume que a tabela não resolve.',
      melhor='Procurar em texto livre e em log com volume alto.',
      para='Busca em produto, observabilidade e análise de log.',
      como='Índices alimentados por pipeline, consultados por busca.',
      mercado='Referência em busca e em análise de log operacional.',
      caso=''),
 # ---------------------------------------------------------------- Governança
 dict(nome='Unity Catalog', grupo='gov', icone='#UC', etapa='todas',
      licenca='Open source', modelo='Gerenciado',
      oque='Catálogo e permissão no Databricks.',
      negocio='Quem vê o quê deixa de ser combinado por e-mail.',
      melhor='Dar uma permissão só que vale para dado, painel e modelo.',
      para='Operação em Databricks com mais de um time no mesmo dado.',
      como='Catálogo central define acesso e linhagem para todo o lakehouse.',
      mercado='Padrão de governança dentro do ecossistema Databricks.',
      caso=''),
 dict(nome='Purview', grupo='gov', icone='#PVW', etapa='todas',
      licenca='Proprietária', modelo='SaaS',
      oque='Governança e linhagem de dados na Azure.',
      negocio='Dá para provar de onde veio cada número.',
      melhor='Mostrar o caminho completo do dado, da origem ao painel.',
      para='Empresa com exigência regulatória ou auditoria frequente.',
      como='Varre as fontes, cataloga e monta a linhagem automaticamente.',
      mercado='Escolha usual de governança em ambiente Azure.',
      caso=''),
 dict(nome='Collibra', grupo='gov', icone='#CLB', etapa='todas',
      licenca='Proprietária', modelo='SaaS',
      oque='Catálogo e governança corporativa.',
      negocio='A regra de dado deixa de ser política no papel.',
      melhor='Transformar política de dados em fluxo que alguém cumpre.',
      para='Corporação com comitê de dados e processo formal.',
      como='Glossário, responsável e fluxo de aprovação por ativo de dado.',
      mercado='Comum em banco e seguradora com governança madura.',
      caso=''),
 dict(nome='Alation', grupo='gov', icone='#ALA', etapa='todas',
      licenca='Proprietária', modelo='SaaS',
      oque='Catálogo com contexto de uso.',
      negocio='Quem usa cada tabela vira informação, não folclore.',
      melhor='Mostrar qual tabela é de fato usada, e por quem.',
      para='Ambiente com muitas tabelas e pouca documentação.',
      como='Lê o log de consultas e deduz o que importa de verdade.',
      mercado='Forte onde a dor é descoberta, não controle.',
      caso=''),
 dict(nome='Atlan', grupo='gov', icone='#ATL', etapa='todas',
      licenca='Proprietária', modelo='SaaS',
      oque='Catálogo colaborativo de dados.',
      negocio='Negócio e engenharia falando da mesma tabela.',
      melhor='Aproximar quem pede o dado de quem constrói o dado.',
      para='Time de dados que atende muitas áreas de negócio.',
      como='Catálogo integrado às ferramentas em que o time já trabalha.',
      mercado='Cresce em times de dados que operam como produto.',
      caso=''),
 dict(nome='dbt tests', grupo='gov', icone='#DBT', etapa='base',
      licenca='Open source', modelo='Biblioteca',
      oque='Validação dentro da própria transformação.',
      negocio='A quebra aparece no pipeline, não na reunião de diretoria.',
      melhor='Barrar dado errado antes que ele chegue ao painel.',
      para='Qualquer base transformada em dbt.',
      como='Teste declarado junto do modelo e executado a cada carga.',
      mercado='Forma mais direta de qualidade no stack moderno.',
      caso=''),
 # ---------------------------------------------------------------- Analytics & DS
 dict(nome='Python', grupo='ds', icone='python', etapa='todas',
      licenca='Open source', modelo='Linguagem',
      oque='Engenharia de dados e modelos preditivos.',
      negocio='O que é repetitivo vira código; o que é previsível vira modelo.',
      melhor='Ir do tratamento do dado ao modelo sem trocar de ferramenta.',
      para='Praticamente toda etapa que exige lógica além do SQL.',
      como='Scripts e notebooks versionados, executados pelo orquestrador.',
      mercado='Linguagem padrão de engenharia de dados e ciência de dados.',
      caso='Modelos de predição de evasão em educação.'),
 dict(nome='SQL', grupo='ds', icone='#SQL', etapa='todas',
      licenca='Padrão aberto', modelo='Linguagem',
      oque='A língua franca do dado.',
      negocio='A lógica sobrevive à troca de ferramenta.',
      melhor='Expressar regra de negócio de forma que qualquer base entende.',
      para='Toda consulta, transformação e definição de métrica.',
      como='Presente do banco de origem ao painel, em toda a cadeia.',
      mercado='Competência mais transferível de toda a área de dados.',
      caso='Presente em toda a engenharia da Atlas.'),
 dict(nome='R', grupo='ds', icone='r', etapa='todas',
      licenca='Open source', modelo='Linguagem',
      oque='Estatística e análise exploratória.',
      negocio='O rigor estatístico entra na decisão.',
      melhor='Fazer estatística séria com ferramental feito para isso.',
      para='Estudo, teste de hipótese e modelagem estatística.',
      como='Análise em script reproduzível, com resultado auditável.',
      mercado='Forte em pesquisa, saúde e áreas de estatística aplicada.',
      caso=''),
 dict(nome='Jupyter', grupo='ds', icone='jupyter', etapa='todas',
      licenca='Open source', modelo='Ferramenta',
      oque='Ambiente de análise e prototipagem.',
      negocio='A hipótese é testada antes de virar projeto.',
      melhor='Misturar código, resultado e explicação no mesmo documento.',
      para='Exploração inicial e comunicação de análise.',
      como='Notebook versionado, com o raciocínio junto do código.',
      mercado='Formato padrão de trabalho exploratório em dados.',
      caso=''),
 dict(nome='pandas', grupo='ds', icone='pandas', etapa='todas',
      licenca='Open source', modelo='Biblioteca',
      oque='Manipulação de dados em Python.',
      negocio='O tratamento vira código revisável, não planilha solta.',
      melhor='Tratar tabela de tamanho médio com poucas linhas de código.',
      para='Limpeza, cruzamento e preparação antes do modelo.',
      como='Carrega, transforma e devolve o dado dentro do pipeline.',
      mercado='Biblioteca mais usada para manipulação tabular em Python.',
      caso=''),
 dict(nome='Polars', grupo='ds', icone='polars', etapa='todas',
      licenca='Open source', modelo='Biblioteca',
      oque='Processamento tabular de alta performance.',
      negocio='Volume médio sem precisar subir um cluster.',
      melhor='Processar milhões de linhas numa máquina só.',
      para='Volume grande demais para planilha, pequeno demais para cluster.',
      como='Substitui o passo pesado do pipeline sem mudar a arquitetura.',
      mercado='Cresce rápido onde o custo de cluster não se justifica.',
      caso=''),
 dict(nome='Dataiku', grupo='ds', icone='dataiku', etapa='base',
      licenca='Proprietária', modelo='SaaS ou self-hosted',
      oque='Plataforma de analytics e IA em baixo código.',
      negocio='O time de negócio participa da construção do modelo.',
      melhor='Deixar quem conhece o negócio montar o fluxo analítico.',
      para='Empresa que quer analytics além do time técnico.',
      como='Fluxo visual, com código onde for necessário.',
      mercado='Presente em corporações que escalam analytics para as áreas.',
      caso=''),
 dict(nome='Alteryx', grupo='ds', icone='alteryx', etapa='base',
      licenca='Proprietária', modelo='Desktop e servidor',
      oque='Preparação e automação analítica visual.',
      negocio='O analista automatiza o próprio fluxo sem virar dev.',
      melhor='Automatizar a rotina que hoje é feita à mão no Excel.',
      para='Área de negócio com processo repetitivo e pesado.',
      como='Fluxo montado visualmente e agendado no servidor.',
      mercado='Forte em finanças e controladoria com rotina manual pesada.',
      caso=''),
]
