import "server-only";
import type { ApiContext } from "@/services/api-context";
import { ApiError } from "@/services/api-context";
import { dashboardSpecSchema, type DashboardSpec } from "@/dashboards/spec";
import type { Dashboard } from "@/types";

export async function getDashboard(ctx: ApiContext, dashboardId: string): Promise<Dashboard> {
  const { data } = await ctx.supabase
    .from("dashboards")
    .select("*")
    .eq("id", dashboardId)
    .eq("workspace_id", ctx.workspaceId)
    .is("deleted_at", null)
    .single();
  if (!data) throw new ApiError(404, "Dashboard not found");
  return data as Dashboard;
}

export function parseSpec(raw: unknown): DashboardSpec {
  const parsed = dashboardSpecSchema.safeParse(raw);
  if (!parsed.success) {
    throw new ApiError(422, "Stored dashboard specification is invalid");
  }
  return parsed.data;
}

export async function createDashboard(
  ctx: ApiContext,
  spec: DashboardSpec,
  options: { generatedByAi?: boolean; description?: string } = {}
): Promise<Dashboard> {
  const { data: dashboard, error } = await ctx.supabase
    .from("dashboards")
    .insert({
      workspace_id: ctx.workspaceId,
      name: spec.name,
      description: options.description ?? spec.purpose ?? null,
      status: "DRAFT",
      spec,
      version: 1,
      generated_by_ai: options.generatedByAi ?? false,
      created_by: ctx.user.id,
    })
    .select()
    .single();
  if (error || !dashboard) throw new ApiError(500, error?.message ?? "Failed to save dashboard");

  await ctx.supabase.from("dashboard_versions").insert({
    workspace_id: ctx.workspaceId,
    dashboard_id: dashboard.id,
    version: 1,
    spec,
    change_summary: options.generatedByAi ? "Generated by Atlas AI" : "Created",
    created_by: ctx.user.id,
  });

  return dashboard as Dashboard;
}

export async function updateDashboardSpec(
  ctx: ApiContext,
  dashboardId: string,
  spec: DashboardSpec,
  changeSummary: string
): Promise<Dashboard> {
  const existing = await getDashboard(ctx, dashboardId);
  const version = existing.version + 1;

  const { data: updated, error } = await ctx.supabase
    .from("dashboards")
    .update({ spec, name: spec.name, version })
    .eq("id", dashboardId)
    .select()
    .single();
  if (error || !updated) throw new ApiError(500, error?.message ?? "Failed to update dashboard");

  await ctx.supabase.from("dashboard_versions").insert({
    workspace_id: ctx.workspaceId,
    dashboard_id: dashboardId,
    version,
    spec,
    change_summary: changeSummary,
    created_by: ctx.user.id,
  });

  return updated as Dashboard;
}
